### ISSUE TITLE
Babel Deprecation (returning a string from a visitor method)

### ISSUE THREAD

**Issue by blimmer** [pangratz/ember-cli-htmlbars-inline-precompile#13]
I've been seeing this on all of my integration tests lately.

```
[BABEL] myapp/tests/integration/components/my-integration-test.js:
Returning a string from a visitor method will be removed in the future.
String building is NOT a substitute for AST generation. 
String building leads to terrible performance due to the additional parsing
overhead and will lead to extremely brittle transformers. For those extreme cases 
where you're dealing with strings from a foreign source you may continue to use 
`path.replaceWithSourceString(code)`. Please don't abuse this. Bad plugins hurt the ecosystem.
```

**Comment by pangratz** [comment]
What version of `ember-cli-htmlbars-inline-precompile`are you using `npm ls ember-cli-htmlbars-inline-precompile`)? This should be fixed in `v0.1.2` ...

**Comment by blimmer** [comment]
This is still happening on `v0.1.2` on my TravisCI build:

I added this to my `.travis.yml`
```
cat node_modules/ember-cli-htmlbars-inline-precompile/package.json
{
  "name": "ember-cli-htmlbars-inline-precompile",
  "version": "0.1.2",
   ...
}
```

and I'm still getting the error. Oddly enough, I'm not getting this when running my tests on OS X. I'm happy to do more debugging if that would be helpful.

**Comment by pangratz** [comment]
Oh boi, I found typo on the PR which should have fixed this. `replaceWithSourceString` -> `replaceWithStringSource`. New version should be up in a few minutes. Thanks for your report!

**Comment by blimmer** [comment]
Nice find! Thank you for the prompt fix :beers:

**Comment by pangratz** [comment]
Okidok, `v0.1.3` is released which should contain the fix. Can you give it a try an close this one if it has been fixed? :beers:

**Comment by blimmer** [comment]
Coming up.

**Comment by blimmer** [comment]
It's fixed with `v0.1.3`. Thanks again.

**Comment by pangratz** [comment]
:+1:
